#!/bin/sh
#-G "MinGW Makefiles"
#build for ninja
#cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF  -Dglew-cmake_BUILD_SHARED=OFF DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -S . -B build -G "Ninja"

#build for vs
cmake -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF  -Dglew-cmake_BUILD_SHARED=OFF DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -S . -B build